# Supabase Configuration

[project]
project_id = "kycuteffcbqizyqlhczc"

[api]
enabled = true
max_body_size = "10 MiB"

[db]
major_version = 15

[realtime]
enabled = true
max_bytes_per_second = 1000000

[auth]
enable_signup = true
enable_anonymous_signups = false

[edge_runtime]
policy = "wasm_only"

[functions."trigger-sos"]
verify_jwt = false
