# Supabase Configuration

[api]
enabled = true

[db]
major_version = 15

[realtime]
enabled = true

[auth]
enable_signup = true

[edge_runtime]
policy = "per_worker"

[functions."trigger-sos"]
verify_jwt = false
